services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "vidova-api"
    ports:
      - "127.0.0.1:8000:8000"
    command: ["python3", "main.py"]
    volumes:
      - ./:/app
    restart: always
