services:
  api:
    image: ghcr.io/pin705/vidova:latest
    container_name: "vidova-api"
    ports:
      - "127.0.0.1:8000:8000"
    command: ["python3", "main.py"]
    volumes:
      - ./apps/render/config.toml:/app/config.toml
      - ./apps/render/storage:/app/storage
    restart: always
